name: Integrate

on: push

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: before_install
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -q update
        sudo apt-get install build-essential git libboost-all-dev cmake libgmp3-dev libssl-dev libsodium-dev libprocps-dev pkg-config gcc-5 g++-5
    - name: before_script
      run: |
        git submodule init && git submodule update
        mkdir build && cd build && cmake ..
    - name: tests
      run: |
        cd build
        make
        make check
  build_macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: before_install
      run: |
        brew install boost
        brew install cmake
        brew install openssl
        brew install gmp
    - name: before_script
      run: |
        git submodule init && git submodule update
        mkdir build && cd build && cmake ..
    - name: tests
      run: |
        cd build
        make
        make check