name: Integrate

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: python_setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 
    - name: before_install
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -q update
        sudo apt-get install build-essential git libboost-all-dev cmake libgmp3-dev libssl-dev libsodium-dev libprocps-dev pkg-config gcc-5 g++-5
        sudo apt-get install clang-tidy
        mkdir build
    - name: wget_clang_tidy_script
      uses: wei/wget@v1
      with:
        args: https://raw.githubusercontent.com/llvm/llvm-project/master/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py -P ./build
    - name: before_script
      run: |
        git submodule init && git submodule update
        cd build
        PATH=$PATH:${PWD} 
        sudo chmod +x run-clang-tidy.py
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DUSE_CLANG_TIDY=ON ..
    - name: run_clang_tidy
      run: |
        cd build
        make clang-tidy
    - name: tests
      run: |
        cd build
        make
        make check

clang-tidy:
  steps:
  - name: run_clang_tidy
    run: |
      cd build
      make clang-
test:
  steps:
  - name: run_tests
    run: |
      cd build
      make
      make check